// Nguồn chân lý duy nhất cho định nghĩa KPI — dùng chung cho Dashboard, Finance, PnL
// Không hardcode công thức rải rác nhiều nơi — mọi component import từ đây
export const KPI_DEFINITIONS = {
  revenue: {
    name: 'Doanh thu thuần',
    formula: 'Tổng tiền bán hàng − Giảm giá & Mã khuyến mãi',
    description: 'Số tiền thực tế thu được từ đơn hàng sau khi trừ toàn bộ chiết khấu và mã giảm giá.',
    businessMeaning: 'Phản ánh quy mô bán hàng thực tế, là điểm khởi đầu của mọi phân tích tài chính.',
    example: 'Tiền hàng 110tr − Giảm giá 10tr = Doanh thu thuần 100tr',
    sourceFields: ['Đơn hàng đã giao thành công'],
    group: 'revenue',
  },
  cogs: {
    name: 'Giá vốn hàng bán (COGS)',
    formula: 'Giá nhập × Số lượng đã bán',
    description: 'Chi phí nhập hàng trực tiếp tương ứng với số sản phẩm đã bán ra.',
    businessMeaning: 'COGS thấp = mua hàng hiệu quả hoặc giá nhập tốt. Kiểm soát COGS giúp tăng biên lợi nhuận.',
    example: 'Giá nhập 150.000đ/áo × 400 áo = Giá vốn 60tr',
    sourceFields: ['Giá nhập từ phiếu mua hàng (NCC)'],
    group: 'revenue',
  },
  grossProfit: {
    name: 'Lợi nhuận gộp',
    formula: 'Doanh thu thuần − Giá vốn hàng bán',
    description: 'Lợi nhuận sau khi trừ chi phí nhập hàng. Chưa tính phí sàn, giao hàng, quảng cáo hay lương.',
    businessMeaning: 'Biên lợi nhuận gộp trên 30% là tốt cho hàng thời trang bán online.',
    example: 'Doanh thu 100tr − Giá vốn 60tr = Lợi nhuận gộp 40tr (tỷ lệ 40%)',
    sourceFields: ['Đơn hàng + giá nhập từ phiếu mua hàng'],
    group: 'revenue',
  },
  grossMargin: {
    name: 'Biên lợi nhuận gộp',
    formula: 'Lợi nhuận gộp ÷ Doanh thu × 100%',
    description: 'Cứ 100 đồng doanh thu thì còn lại bao nhiêu đồng sau khi trừ giá nhập hàng.',
    businessMeaning: 'Nếu tỷ lệ này dưới 30%, cần xem lại giá nhập hoặc điều chỉnh giá bán.',
    example: 'Lợi nhuận gộp 40tr ÷ Doanh thu 100tr = Biên gộp 40%',
    sourceFields: ['Đơn hàng + giá nhập từ phiếu mua hàng'],
    group: 'revenue',
  },
  platformFee: {
    name: 'Phí sàn vận hành',
    formula: 'Phí hoa hồng sàn + Phí thanh toán + Chi phí đóng gói + Phí giao hàng',
    description: 'Toàn bộ chi phí liên quan đến việc bán hàng trên sàn TMĐT: hoa hồng, thanh toán, đóng gói, vận chuyển.',
    businessMeaning: 'Tổng phí dưới 15% doanh thu là hợp lý. Trên 20% cần đàm phán lại hoặc điều chỉnh giá bán.',
    example: 'Hoa hồng Shopee 4% + Phí TT 1.5% + Vận chuyển 3% = ~8.5% doanh thu',
    sourceFields: ['Cấu hình phí sàn trong phần Tài chính'],
    group: 'operating',
  },
  operatingProfit: {
    name: 'Lợi nhuận vận hành',
    formula: 'Lợi nhuận gộp − Phí sàn − Phí giao hàng − Chi phí quảng cáo',
    description: 'Lợi nhuận thực tế sau khi trừ toàn bộ chi phí bán hàng trực tiếp và quảng cáo. Đây là KPI quan trọng nhất với shop online.',
    businessMeaning: 'Nếu lợi nhuận vận hành âm: shop đang lỗ từ hoạt động bán hàng, cần giảm chi phí ngay.',
    example: 'LN gộp 40tr − Phí sàn 4tr − Phí ship 3tr − Quảng cáo 5tr = LN vận hành 28tr',
    sourceFields: ['Đơn hàng + Chi phí quảng cáo nhập tay theo tháng'],
    group: 'operating',
  },
  operatingMargin: {
    name: 'Biên lợi nhuận vận hành',
    formula: 'Lợi nhuận vận hành ÷ Doanh thu × 100%',
    description: 'Cứ 100 đồng doanh thu thì còn lại bao nhiêu đồng sau tất cả chi phí bán hàng.',
    businessMeaning: 'Tỷ lệ dưới 5%: kinh doanh biên mỏng, rủi ro cao. Trên 20%: rất hiệu quả.',
    example: 'LN vận hành 28tr ÷ Doanh thu 100tr = Biên vận hành 28%',
    sourceFields: ['Đơn hàng + Chi phí quảng cáo nhập tay theo tháng'],
    group: 'operating',
  },
  netAfterFees: {
    name: 'LN sau phí sàn',
    formula: 'Lợi nhuận gộp − Phí hoa hồng sàn − Phí thanh toán − Chi phí đóng gói − Phí giao hàng',
    description: 'Lợi nhuận sau khi trừ toàn bộ phí sàn và vận chuyển. Chưa tính chi phí quảng cáo.',
    businessMeaning: 'Nếu âm: không chạy quảng cáo cũng đã lỗ từ phí sàn — cần điều chỉnh giá bán.',
    example: 'LN gộp 40tr − Phí sàn 8tr − Phí ship 3tr = LN sau phí sàn 29tr',
    sourceFields: ['Đơn hàng + Cấu hình phí sàn'],
    group: 'operating',
  },
  adSpend: {
    name: 'Chi phí quảng cáo',
    formula: 'Tổng tiền chi cho quảng cáo tất cả kênh trong kỳ',
    description: 'Tổng chi phí quảng cáo nhập tay theo kênh và tháng: Shopee Ads, TikTok Ads, Lazada Ads...',
    businessMeaning: 'Chi phí quảng cáo dưới 20% doanh thu là hiệu quả. Nếu chưa nhập → ROAS và ACOS không tính được.',
    example: 'Shopee 5tr + TikTok 8tr + Lazada 3tr = Tổng QC tháng 5: 16tr',
    sourceFields: ['Chi phí quảng cáo nhập tay theo kênh/tháng'],
    group: 'marketing',
  },
  roas: {
    name: 'ROAS — Hiệu quả quảng cáo',
    formula: 'Doanh thu ÷ Chi phí quảng cáo',
    description: 'Cứ 1 đồng chi cho quảng cáo thì thu về bao nhiêu đồng doanh thu. ROAS từ 4× trở lên là hiệu quả.',
    businessMeaning: 'ROAS dưới 2×: cần xem lại nội dung quảng cáo hoặc nhắm mục tiêu.',
    example: 'Chi QC 10tr, doanh thu 50tr → ROAS = 5× (tốt). ROAS = 1.5× → đang lỗ quảng cáo',
    sourceFields: ['Chi phí quảng cáo nhập tay + Đơn hàng'],
    group: 'marketing',
  },
  acos: {
    name: 'ACOS — Tỷ lệ chi phí quảng cáo',
    formula: 'Chi phí quảng cáo ÷ Doanh thu × 100%',
    description: 'Cứ 100 đồng doanh thu thì mất bao nhiêu đồng cho quảng cáo. ACOS thấp = quảng cáo hiệu quả hơn.',
    businessMeaning: 'ACOS mục tiêu dưới 15–20% cho hàng thời trang online. ACOS = 100% ÷ ROAS.',
    example: 'ACOS 20% = cứ 100đ doanh thu thì chi 20đ QC → tương đương ROAS = 5×',
    sourceFields: ['Chi phí quảng cáo nhập tay + Đơn hàng'],
    group: 'marketing',
  },
  orders: {
    name: 'Số đơn hàng',
    formula: 'Tổng số đơn phát sinh trong kỳ đã chọn',
    description: 'Đếm tất cả đơn hàng tạo ra trong khoảng thời gian bạn chọn, bao gồm mọi trạng thái.',
    businessMeaning: 'Số đơn tăng nhưng doanh thu không tăng → giá bán giảm hoặc nhiều đơn nhỏ hơn trước.',
    example: '320 đơn/tháng = trung bình khoảng 10 đơn/ngày',
    sourceFields: ['Đơn hàng trong hệ thống'],
    group: 'customer',
  },
  aov: {
    name: 'Giá trị đơn trung bình (AOV)',
    formula: 'Doanh thu thuần ÷ Số đơn hàng',
    description: 'Mỗi đơn hàng trung bình mang lại bao nhiêu doanh thu.',
    businessMeaning: 'Tăng giá trị đơn bằng cách bán kèm, combo, hoặc upsell — hiệu quả hơn là chỉ tăng số đơn.',
    example: 'Doanh thu 100tr ÷ 200 đơn = Giá trị trung bình 500.000đ/đơn',
    sourceFields: ['Đơn hàng đã giao thành công'],
    group: 'customer',
  },
  newCustomers: {
    name: 'Khách hàng mới',
    formula: 'Số khách đặt đơn lần đầu tiên trong kỳ',
    description: 'Đếm những khách hàng xuất hiện lần đầu trong khoảng thời gian bạn chọn.',
    businessMeaning: 'Khách mới tốn chi phí quảng cáo cao hơn khách cũ. Cần giữ chân khách cũ song song với thu hút khách mới.',
    example: 'Tháng này 85 khách mới → tăng 12% so tháng trước → chiến lược quảng cáo đang hiệu quả',
    sourceFields: ['Hồ sơ khách hàng + Đơn hàng'],
    group: 'customer',
  },
  retentionRate: {
    name: 'Tỷ lệ khách quay lại',
    formula: 'Số khách mua từ 2 lần trở lên ÷ Tổng khách hàng × 100%',
    description: 'Tỷ lệ khách hàng quay lại mua thêm ít nhất một lần nữa. Tỷ lệ cao cho thấy sản phẩm và dịch vụ được khách tin dùng.',
    businessMeaning: 'Chi phí giữ khách cũ thường thấp hơn 5 lần so với tìm khách mới.',
    example: 'Tỷ lệ 40% = cứ 10 khách thì 4 người quay lại mua thêm. Ngành thời trang tốt: 30–50%',
    sourceFields: ['Hồ sơ khách hàng + Đơn hàng'],
    group: 'customer',
  },
  conversionRate: {
    name: 'Tỷ lệ chuyển đổi',
    formula: 'Số đơn hàng ÷ Số lượt xem sản phẩm × 100%',
    description: 'Cứ 100 người xem sản phẩm thì bao nhiêu người thực sự đặt mua. Cần dữ liệu lượt xem từ sàn TMĐT.',
    businessMeaning: 'Tỷ lệ thấp → cần cải thiện ảnh sản phẩm, mô tả, đánh giá hoặc điều chỉnh giá.',
    example: 'Tỷ lệ 3% = cứ 100 lượt xem thì 3 người đặt hàng. Thời trang online: 2–5% là bình thường',
    sourceFields: ['Dữ liệu lượt xem từ Shopee, Lazada, TikTok Shop'],
    group: 'customer',
  },
  businessNetProfit: {
    name: 'Lợi nhuận doanh nghiệp ròng',
    formula: 'Lợi nhuận vận hành − Lương nhân viên − Chi phí kho & điện nước',
    description: 'Lợi nhuận cuối cùng sau khi trừ tất cả chi phí vận hành doanh nghiệp (lương, kho, điện, internet...)',
    businessMeaning: 'Đây là số tiền thực sự còn lại sau mọi chi phí — "lợi nhuận thật" của doanh nghiệp.',
    example: 'LN vận hành 28tr − Lương 10tr − Kho 3tr − Điện 1tr = LN ròng 14tr',
    sourceFields: ['Đơn hàng + Chi phí quảng cáo + Chi phí vận hành nhập tay'],
    group: 'pnl',
  },
}

// Nhóm KPI để hiển thị có tổ chức
export const KPI_GROUPS = {
  revenue:  { label: 'Doanh thu & Chi phí hàng', icon: 'payments',          color: '#6366F1' },
  operating:{ label: 'Hiệu quả vận hành',         icon: 'trending_up',       color: '#10B981' },
  marketing:{ label: 'Hiệu quả quảng cáo',        icon: 'ads_click',         color: '#EC4899' },
  customer: { label: 'Khách hàng',                 icon: 'people',            color: '#3B82F6' },
  pnl:      { label: 'P&L tổng hợp',              icon: 'account_balance',   color: '#8B5CF6' },
}
