// Nguồn chân lý duy nhất cho định nghĩa KPI — dùng chung cho Dashboard, Finance, PnL
// Không hardcode công thức rải rác nhiều nơi — mọi component import từ đây
import i18n from '../i18n'

const isEn = () => i18n.language === 'en'

export const KPI_DEFINITIONS = {
  revenue: {
    get name() { return isEn() ? 'Net Revenue' : 'Doanh thu thuần' },
    get formula() { return isEn() ? 'Total sales − Discounts & Promos' : 'Tổng tiền bán hàng − Giảm giá & Mã khuyến mãi' },
    get description() { return isEn() ? 'Actual money earned from orders after subtracting all discounts and vouchers.' : 'Số tiền thực tế thu được từ đơn hàng sau khi trừ toàn bộ chiết khấu và mã giảm giá.' },
    get businessMeaning() { return isEn() ? 'Reflects actual sales volume, the starting point of all financial analysis.' : 'Phản ánh quy mô bán hàng thực tế, là điểm khởi đầu của mọi phân tích tài chính.' },
    get example() { return isEn() ? 'Item revenue 110,000,000đ − Discount 10,000,000đ = Net Revenue 100,000,000đ' : 'Tiền hàng 110.000.000đ − Giảm giá 10.000.000đ = Doanh thu thuần 100.000.000đ' },
    get sourceFields() { return isEn() ? ['Successfully delivered orders'] : ['Đơn hàng đã giao thành công'] },
    group: 'revenue',
  },
  cogs: {
    get name() { return isEn() ? 'Cost of Goods Sold (COGS)' : 'Giá vốn hàng bán (COGS)' },
    get formula() { return isEn() ? 'Cost Price × Quantity Sold' : 'Giá nhập × Số lượng đã bán' },
    get description() { return isEn() ? 'Direct cost of purchasing the products sold.' : 'Chi phí nhập hàng trực tiếp tương ứng với số sản phẩm đã bán ra.' },
    get businessMeaning() { return isEn() ? 'Low COGS = efficient purchasing. Controlling COGS helps increase profit margins.' : 'COGS thấp = mua hàng hiệu quả hoặc giá nhập tốt. Kiểm soát COGS giúp tăng biên lợi nhuận.' },
    get example() { return isEn() ? 'Cost price 150,000đ/item × 400 items = COGS 60,000,000đ' : 'Giá nhập 150.000đ/áo × 400 áo = Giá vốn 60.000.000đ' },
    get sourceFields() { return isEn() ? ['Cost price from Purchase Orders (Supplier)'] : ['Giá nhập từ phiếu mua hàng (NCC)'] },
    group: 'revenue',
  },
  grossProfit: {
    get name() { return isEn() ? 'Gross Profit' : 'Lợi nhuận gộp' },
    get formula() { return isEn() ? 'Net Revenue − Cost of Goods Sold' : 'Doanh thu thuần − Giá vốn hàng bán' },
    get description() { return isEn() ? 'Profit after subtracting product purchasing costs. Excludes platform fees, delivery, ads, or payroll.' : 'Lợi nhuận sau khi trừ chi phí nhập hàng. Chưa tính phí sàn, giao hàng, quảng cáo hay lương.' },
    get businessMeaning() { return isEn() ? 'Gross margin above 30% is good for e-commerce fashion.' : 'Biên lợi nhuận gộp trên 30% là tốt cho hàng thời trang bán online.' },
    get example() { return isEn() ? 'Revenue 100,000,000đ − COGS 60,000,000đ = Gross Profit 40,000,000đ (40% margin)' : 'Doanh thu 100.000.000đ − Giá vốn 60.000.000đ = Lợi nhuận gộp 40.000.000đ (tỷ lệ 40%)' },
    get sourceFields() { return isEn() ? ['Orders + Cost price from purchase orders'] : ['Đơn hàng + giá nhập từ phiếu mua hàng'] },
    group: 'revenue',
  },
  grossMargin: {
    get name() { return isEn() ? 'Gross Margin' : 'Biên lợi nhuận gộp' },
    get formula() { return isEn() ? 'Gross Profit ÷ Revenue × 100%' : 'Lợi nhuận gộp ÷ Doanh thu × 100%' },
    get description() { return isEn() ? 'For every 100đ of revenue, how much remains after product purchasing costs.' : 'Cứ 100 đồng doanh thu thì còn lại bao nhiêu đồng sau khi trừ giá nhập hàng.' },
    get businessMeaning() { return isEn() ? 'If this ratio is under 30%, consider raising prices or renegotiating cost price.' : 'Nếu tỷ lệ này dưới 30%, cần xem lại giá nhập hoặc điều chỉnh giá bán.' },
    get example() { return isEn() ? 'Gross Profit 40,000,000đ ÷ Revenue 100,000,000đ = Gross Margin 40%' : 'Lợi nhuận gộp 40.000.000đ ÷ Doanh thu 100.000.000đ = Biên gộp 40%' },
    get sourceFields() { return isEn() ? ['Orders + Cost price from purchase orders'] : ['Đơn hàng + giá nhập từ phiếu mua hàng'] },
    group: 'revenue',
  },
  platformFee: {
    get name() { return isEn() ? 'Platform & Payment Fees' : 'Phí sàn & thanh toán' },
    get formula() { return isEn() ? 'Platform Commission + Payment Fee + Packaging Cost + Shipping Fee' : 'Phí hoa hồng sàn + Phí thanh toán + Chi phí đóng gói + Phí giao hàng' },
    get description() { return isEn() ? 'Direct selling fees by channel/platform, estimated from fee configurations. This is not operating expense.' : 'Các khoản phí bán hàng trực tiếp phát sinh theo kênh/sàn, được ước tính từ cấu hình phí. Khoản này không phải chi phí vận hành doanh nghiệp nhập tay trong P&L.' },
    get businessMeaning() { return isEn() ? 'Total fees under 15% of revenue is reasonable. Above 20% needs review of fee configuration, platform policy, or pricing.' : 'Tổng phí dưới 15% doanh thu là hợp lý. Trên 20% cần rà soát cấu hình phí, chính sách sàn hoặc điều chỉnh giá bán.' },
    get example() { return isEn() ? 'Shopee commission 4% + Payment fee 1.5% + Shipping 3% = ~8.5% of revenue' : 'Hoa hồng Shopee 4% + Phí TT 1.5% + Vận chuyển 3% = ~8.5% doanh thu' },
    get sourceFields() { return isEn() ? ['Platform fee configuration in Finance'] : ['Cấu hình phí sàn trong phần Tài chính'] },
    group: 'operating',
  },
  operatingProfit: {
    get name() { return isEn() ? 'Operating Profit' : 'Lợi nhuận vận hành' },
    get formula() { return isEn() ? 'Net After Fees − Ad Spend' : 'LN sau phí sàn − Chi phí quảng cáo' },
    get description() { return isEn() ? 'Profit after subtracting COGS, platform/payment/packaging/shipping fees, and ad spend. Excludes manual operating expenses like salary, warehouse rent, utilities.' : 'Lợi nhuận sau khi trừ giá vốn, phí sàn/thanh toán/đóng gói/vận chuyển và chi phí quảng cáo. Chưa trừ manual operating expenses như lương, kho, điện nước.' },
    get businessMeaning() { return isEn() ? 'If negative, sales after advertising are not profitable. Review prices, COGS, fees, or ad budget.' : 'Nếu lợi nhuận vận hành âm: hoạt động bán hàng sau quảng cáo đang không hiệu quả, cần rà soát giá bán, COGS, phí sàn hoặc ngân sách QC.' },
    get example() { return isEn() ? 'Net After Fees 33,000,000đ − Ad Spend 5,000,000đ = Operating Profit 28,000,000đ' : 'LN sau phí sàn 33.000.000đ − Quảng cáo 5.000.000đ = LN vận hành 28.000.000đ' },
    get sourceFields() { return isEn() ? ['Orders + Ad spend input by month'] : ['Đơn hàng + Chi phí quảng cáo nhập tay theo tháng'] },
    group: 'operating',
  },
  operatingMargin: {
    get name() { return isEn() ? 'Operating Margin' : 'Biên lợi nhuận vận hành' },
    get formula() { return isEn() ? 'Operating Profit ÷ Revenue × 100%' : 'Lợi nhuận vận hành ÷ Doanh thu × 100%' },
    get description() { return isEn() ? 'For every 100đ of revenue, how much remains after all selling costs.' : 'Cứ 100 đồng doanh thu thì còn lại bao nhiêu đồng sau tất cả chi phí bán hàng.' },
    get businessMeaning() { return isEn() ? 'Below 5%: thin margins, high risk. Above 20%: highly efficient.' : 'Tỷ lệ dưới 5%: kinh doanh biên mỏng, rủi ro cao. Trên 20%: rất hiệu quả.' },
    get example() { return isEn() ? 'Operating Profit 28,000,000đ ÷ Revenue 100,000,000đ = Operating Margin 28%' : 'LN vận hành 28.000.000đ ÷ Doanh thu 100.000.000đ = Biên vận hành 28%' },
    get sourceFields() { return isEn() ? ['Orders + Ad spend input by month'] : ['Đơn hàng + Chi phí quảng cáo nhập tay theo tháng'] },
    group: 'operating',
  },
  netAfterFees: {
    get name() { return isEn() ? 'Net After Fees' : 'LN sau phí sàn' },
    get formula() { return isEn() ? 'Gross Profit − Commission − Payment Fee − Packaging − Shipping' : 'Lợi nhuận gộp − Phí hoa hồng sàn − Phí thanh toán − Chi phí đóng gói − Phí giao hàng' },
    get description() { return isEn() ? 'Profit after subtracting all platform, payment, packaging, and shipping fees. Excludes ad spend and manual operating expenses.' : 'Lợi nhuận sau khi trừ toàn bộ phí sàn, thanh toán, đóng gói và vận chuyển. Chưa tính chi phí quảng cáo và manual operating expenses.' },
    get businessMeaning() { return isEn() ? 'If negative, selling is unprofitable even without ads — adjust pricing.' : 'Nếu âm: không chạy quảng cáo cũng đã lỗ từ phí sàn — cần điều chỉnh giá bán.' },
    get example() { return isEn() ? 'Gross Profit 40,000,000đ − Platform Fees 8,000,000đ − Shipping 3,000,000đ = Net After Fees 29,000,000đ' : 'LN gộp 40.000.000đ − Phí sàn 8.000.000đ − Phí ship 3.000.000đ = LN sau phí sàn 29.000.000đ' },
    get sourceFields() { return isEn() ? ['Orders + Platform fee configuration'] : ['Đơn hàng + Cấu hình phí sàn'] },
    group: 'operating',
  },
  adSpend: {
    get name() { return isEn() ? 'Ad Spend' : 'Chi phí quảng cáo' },
    get formula() { return isEn() ? 'Total ad spend across all channels in the period' : 'Tổng tiền chi cho quảng cáo tất cả kênh trong kỳ' },
    get description() { return isEn() ? 'Total ad spend input by channel and month: Shopee Ads, TikTok Ads, Lazada Ads... For date ranges, the system allocates month values proportionally.' : 'Tổng chi phí quảng cáo nhập tay theo kênh và tháng: Shopee Ads, TikTok Ads, Lazada Ads... Khi lọc theo khoảng ngày, hệ thống dùng các tháng quảng cáo giao với khoảng ngày đó.' },
    get businessMeaning() { return isEn() ? 'Ad spend under 20% of revenue is efficient. If not input, ROAS and ACOS cannot be calculated.' : 'Chi phí quảng cáo dưới 20% doanh thu là hiệu quả. Nếu chưa nhập → ROAS và ACOS không tính được.' },
    get example() { return isEn() ? 'Shopee 5,000,000đ + TikTok 8,000,000đ + Lazada 3,000,000đ = Total Ad Spend 16,000,000đ' : 'Shopee 5.000.000đ + TikTok 8.000.000đ + Lazada 3.000.000đ = Tổng QC tháng 5: 16.000.000đ' },
    get sourceFields() { return isEn() ? ['Ad spend input by channel/month'] : ['Chi phí quảng cáo nhập tay theo kênh/tháng'] },
    group: 'marketing',
  },
  roas: {
    get name() { return isEn() ? 'ROAS — Return on Ad Spend' : 'ROAS — Hiệu quả quảng cáo' },
    get formula() { return isEn() ? 'Revenue ÷ Ad Spend' : 'Doanh thu ÷ Chi phí quảng cáo' },
    get description() { return isEn() ? 'Revenue generated for every 1đ spent on advertising. ROAS of 4× or more is efficient.' : 'Cử 1 đồng chi cho quảng cáo thì thu về bao nhiêu đồng doanh thu. ROAS từ 4× trở lên là hiệu quả.' },
    get businessMeaning() { return isEn() ? 'ROAS below 2×: consider reviewing ad creatives or targeting.' : 'ROAS dưới 2×: cần xem lại nội dung quảng cáo hoặc nhắm mục tiêu.' },
    get example() { return isEn() ? 'Ad Spend 10,000,000đ, Revenue 50,000,000đ → ROAS = 5×. ROAS = 1.5× → losing money on ads' : 'Chi QC 10.000.000đ, doanh thu 50.000.000đ → ROAS = 5× (tốt). ROAS = 1.5× → đang lỗ quảng cáo' },
    get sourceFields() { return isEn() ? ['Ad spend input + Orders'] : ['Chi phí quảng cáo nhập tay + Đơn hàng'] },
    group: 'marketing',
  },
  acos: {
    get name() { return isEn() ? 'ACOS — Advertising Cost of Sales' : 'ACOS — Tỷ lệ chi phí quảng cáo' },
    get formula() { return isEn() ? 'Ad Spend ÷ Revenue × 100%' : 'Chi phí quảng cáo ÷ Doanh thu × 100%' },
    get description() { return isEn() ? 'Percentage of revenue spent on advertising. Lower ACOS = more efficient advertising.' : 'Cử 100 đồng doanh thu thì mất bao nhiêu đồng cho quảng cáo. ACOS thấp = quảng cáo hiệu quả hơn.' },
    get businessMeaning() { return isEn() ? 'Target ACOS under 15–20% for e-commerce fashion. ACOS = 100% ÷ ROAS.' : 'ACOS mục tiêu dưới 15–20% cho hàng thời trang online. ACOS = 100% ÷ ROAS.' },
    get example() { return isEn() ? 'ACOS 20% = for every 100đ of revenue, 20đ is spent on ads → equivalent to ROAS = 5×' : 'ACOS 20% = cứ 100đ doanh thu thì chi 20đ QC → tương đương ROAS = 5×' },
    get sourceFields() { return isEn() ? ['Ad spend input + Orders'] : ['Chi phí quảng cáo nhập tay + Đơn hàng'] },
    group: 'marketing',
  },
  orders: {
    get name() { return isEn() ? 'Total Orders' : 'Số đơn hàng' },
    get formula() { return isEn() ? 'Total orders in the selected period' : 'Tổng số đơn phát sinh trong kỳ đã chọn' },
    get description() { return isEn() ? 'Count of all orders created in the selected date range, including all statuses.' : 'Đếm tất cả đơn hàng tạo ra trong khoảng thời gian bạn chọn, bao gồm mọi trạng thái.' },
    get businessMeaning() { return isEn() ? 'Orders increasing but revenue stable → average price dropped or more small orders.' : 'Số đơn tăng nhưng doanh thu không tăng → giá bán giảm hoặc nhiều đơn nhỏ hơn trước.' },
    get example() { return isEn() ? '320 orders/month = average of ~10 orders/day' : '320 đơn/tháng = trung bình khoảng 10 đơn/ngày' },
    get sourceFields() { return isEn() ? ['Orders in system'] : ['Đơn hàng trong hệ thống'] },
    group: 'customer',
  },
  aov: {
    get name() { return isEn() ? 'Avg. Order Value (AOV)' : 'Giá trị đơn trung bình (AOV)' },
    get formula() { return isEn() ? 'Net Revenue ÷ Total Orders' : 'Doanh thu thuần ÷ Số đơn hàng' },
    get description() { return isEn() ? 'Average revenue generated per order.' : 'Mỗi đơn hàng trung bình mang lại bao nhiêu doanh thu.' },
    get businessMeaning() { return isEn() ? 'Increase AOV by bundling, combos, or upselling — more efficient than just increasing order count.' : 'Tăng giá trị đơn bằng cách bán kèm, combo, hoặc upsell — hiệu quả hơn là chỉ tăng số đơn.' },
    get example() { return isEn() ? 'Revenue 100,000,000đ ÷ 200 orders = AOV 500,000đ/order' : 'Doanh thu 100.000.000đ ÷ 200 đơn = Giá trị trung bình 500.000đ/đơn' },
    get sourceFields() { return isEn() ? ['Successfully delivered orders'] : ['Đơn hàng đã giao thành công'] },
    group: 'customer',
  },
  newCustomers: {
    get name() { return isEn() ? 'New Customers' : 'Khách hàng mới' },
    get formula() { return isEn() ? 'Customers placing their first order in the period' : 'Số khách đặt đơn lần đầu tiên trong kỳ' },
    get description() { return isEn() ? 'Count of customers appearing for the first time in the selected date range.' : 'Đếm những khách hàng xuất hiện lần đầu trong khoảng thời gian bạn chọn.' },
    get businessMeaning() { return isEn() ? 'Acquiring new customers costs more than retaining existing ones. Balance both strategies.' : 'Khách mới tốn chi phí quảng cáo cao hơn khách cũ. Cần giữ chân khách cũ song song với thu hút khách mới.' },
    get example() { return isEn() ? '85 new customers this month → up 12% → marketing campaign is effective' : 'Tháng này 85 khách mới → tăng 12% so tháng trước → chiến lược quảng cáo đang hiệu quả' },
    get sourceFields() { return isEn() ? ['Customer profiles + Orders'] : ['Hồ sơ khách hàng + Đơn hàng'] },
    group: 'customer',
  },
  retentionRate: {
    get name() { return isEn() ? 'Retention Rate' : 'Tỷ lệ khách quay lại' },
    get formula() { return isEn() ? 'Repeat Customers ÷ Total Customers × 100%' : 'Số khách mua từ 2 lần trở lên ÷ Tổng khách hàng × 100%' },
    get description() { return isEn() ? 'Percentage of customers who purchase 2 or more times. High retention indicates product/service satisfaction.' : 'Tỷ lệ khách hàng quay lại mua thêm ít nhất một lần nữa. Tỷ lệ cao cho thấy sản phẩm và dịch vụ được khách tin dùng.' },
    get businessMeaning() { return isEn() ? 'Retaining an existing customer is 5 times cheaper than finding a new one.' : 'Chi phí giữ khách cũ thường thấp hơn 5 lần so với tìm khách mới.' },
    get example() { return isEn() ? '40% retention = 4 out of 10 customers return. Good fashion benchmark: 30–50%' : 'Tỷ lệ 40% = cứ 10 khách thì 4 người quay lại mua thêm. Ngành thời trang tốt: 30–50%' },
    get sourceFields() { return isEn() ? ['Customer profiles + Orders'] : ['Hồ sơ khách hàng + Đơn hàng'] },
    group: 'customer',
  },
  conversionRate: {
    get name() { return isEn() ? 'Conversion Rate' : 'Tỷ lệ chuyển đổi' },
    get formula() { return isEn() ? 'Total Orders ÷ Product Views × 100%' : 'Số đơn hàng ÷ Số lượt xem sản phẩm × 100%' },
    get description() { return isEn() ? 'Percentage of product views that turn into orders. Requires view data from e-commerce platforms.' : 'Cứ 100 người xem sản phẩm thì bao nhiêu người thực sự đặt mua. Cần dữ liệu lượt xem từ sàn TMĐT.' },
    get businessMeaning() { return isEn() ? 'Low conversion → improve product images, descriptions, reviews, or adjust price.' : 'Tỷ lệ thấp → cần cải thiện ảnh sản phẩm, mô tả, đánh giá hoặc điều chỉnh giá.' },
    get example() { return isEn() ? '3% conversion = 3 orders per 100 views. Fashion benchmark: 2–5% is normal' : 'Tỷ lệ 3% = cứ 100 lượt xem thì 3 người đặt hàng. Thời trang online: 2–5% là bình thường' },
    get sourceFields() { return isEn() ? ['View data from Shopee, Lazada, TikTok Shop'] : ['Dữ liệu lượt xem từ Shopee, Lazada, TikTok Shop'] },
    group: 'customer',
  },
  businessNetProfit: {
    get name() { return isEn() ? 'Business Net Profit' : 'Lợi nhuận doanh nghiệp ròng' },
    get formula() { return isEn() ? 'Operating Profit − Manual Operating Expenses' : 'Lợi nhuận vận hành − Chi phí vận hành doanh nghiệp nhập tay' },
    get description() { return isEn() ? 'Final profit after subtracting manual operating expenses (salary, warehouse rent, utilities, office, etc.).' : 'Lợi nhuận cuối cùng sau khi trừ các chi phí vận hành doanh nghiệp nhập tay như lương, kho, điện, internet, văn phòng phẩm và chi phí khác.' },
    get businessMeaning() { return isEn() ? 'Actual money left after all expenses — the "real profit" of the business.' : 'Đây là số tiền thực sự còn lại sau mọi chi phí — "lợi nhuận thật" của doanh nghiệp.' },
    get example() { return isEn() ? 'Operating Profit 28,000,000đ − Salaries 10,000,000đ − Rent 3,000,000đ − Utilities 1,000,000đ = Net Profit 14,000,000đ' : 'LN vận hành 28.000.000đ − Lương 10.000.000đ − Kho 3.000.000đ − Điện 1.000.000đ = LN ròng 14.000.000đ' },
    get sourceFields() { return isEn() ? ['Orders + Ad spend + Manual operating expenses'] : ['Đơn hàng + Chi phí quảng cáo + Chi phí vận hành nhập tay'] },
    group: 'pnl',
  },
}

export const KPI_GROUPS = {
  revenue:  { get label() { return isEn() ? 'Revenue & Costs' : 'Doanh thu & Chi phí hàng' }, icon: 'payments',          color: '#6366F1' },
  operating:{ get label() { return isEn() ? 'Operating Efficiency' : 'Hiệu quả vận hành' },         icon: 'trending_up',       color: '#10B981' },
  marketing:{ get label() { return isEn() ? 'Advertising Efficiency' : 'Hiệu quả quảng cáo' },        icon: 'ads_click',         color: '#EC4899' },
  customer: { get label() { return isEn() ? 'Customers' : 'Khách hàng' },                 icon: 'people',            color: '#3B82F6' },
  pnl:      { get label() { return isEn() ? 'Integrated P&L' : 'P&L tổng hợp' },              icon: 'account_balance',   color: '#8B5CF6' },
}
