// Nguồn chân lý duy nhất cho định nghĩa KPI — dùng chung cho Dashboard, Finance, PnL
// Không hardcode công thức rải rác nhiều nơi — mọi component import từ đây
export const KPI_DEFINITIONS = {
  revenue: {
    name: 'Doanh thu thuần',
    formula: 'Tổng doanh thu − Chiết khấu',
    description: 'Số tiền thực tế thu được từ đơn hàng sau khi trừ toàn bộ chiết khấu và mã giảm giá.',
    businessMeaning: 'Phản ánh quy mô bán hàng thực tế, là điểm khởi đầu của mọi phân tích tài chính.',
    example: 'Doanh thu gốc 110tr − Chiết khấu 10tr = Doanh thu thuần 100tr',
    sourceFields: ['dw.fact_sales.net_revenue'],
    group: 'revenue',
  },
  cogs: {
    name: 'Giá vốn hàng bán (COGS)',
    formula: 'Giá vốn × Số lượng bán',
    description: 'Chi phí nhập hàng trực tiếp để tạo ra sản phẩm đã bán.',
    businessMeaning: 'COGS thấp = mua hàng hiệu quả hoặc giá nhập tốt. Kiểm soát COGS giúp tăng biên lợi nhuận.',
    example: 'Giá vốn 150k/áo × 400 áo = COGS 60tr',
    sourceFields: ['products.cost_price', 'dw.fact_sales.cogs_amount'],
    group: 'revenue',
  },
  grossProfit: {
    name: 'Lợi nhuận gộp',
    formula: 'Doanh thu thuần − COGS',
    description: 'Lợi nhuận sau khi trừ chi phí nhập hàng. Chưa trừ phí sàn, vận chuyển, QC hay chi phí vận hành.',
    businessMeaning: 'Chỉ số hiệu quả sản xuất/nhập hàng. Biên gộp > 30% là tốt cho thời trang B2C.',
    example: 'Doanh thu 100tr − COGS 60tr = Lợi nhuận gộp 40tr (Biên 40%)',
    sourceFields: ['dw.fact_sales.gross_profit'],
    group: 'revenue',
  },
  grossMargin: {
    name: 'Biên lợi nhuận gộp',
    formula: 'Lợi nhuận gộp ÷ Doanh thu × 100%',
    description: 'Phần trăm doanh thu còn lại sau khi trừ giá vốn. Ngành thời trang thường 40–60%.',
    businessMeaning: 'Nếu biên gộp < 30%, cần xem lại giá nhập hoặc giá bán.',
    example: 'LN gộp 40tr ÷ Doanh thu 100tr = Biên LN gộp 40%',
    sourceFields: ['dw.fact_sales.gross_profit', 'dw.fact_sales.net_revenue'],
    group: 'revenue',
  },
  platformFee: {
    name: 'Phí sàn vận hành',
    formula: 'Platform fee + Payment fee + Packaging + Shipping',
    description: 'Toàn bộ phí bán hàng trên sàn TMĐT: phí hoa hồng, phí thanh toán, đóng gói, vận chuyển.',
    businessMeaning: 'Phí < 15% doanh thu là hợp lý. Phí > 20% cần đàm phán lại với sàn.',
    example: 'Shopee fee 4% + Payment 1.5% + Ship 3% = Phí ~8.5% doanh thu',
    sourceFields: ['dw.fact_sales.estimated_total_fee', 'channel_fee_configs'],
    group: 'operating',
  },
  operatingProfit: {
    name: 'Lợi nhuận vận hành',
    formula: 'LN gộp − Phí sàn − Phí thanh toán − Shipping − Chi phí QC',
    description: 'Lợi nhuận thực tế sau tất cả chi phí bán hàng trực tiếp và quảng cáo. KPI quan trọng nhất với shop online.',
    businessMeaning: 'Nếu Operating Profit âm: shop đang lỗ từ hoạt động bán hàng, cần giảm chi phí ngay.',
    example: 'LN gộp 40tr − Phí sàn 4tr − Phí ship 3tr − QC 5tr = LN vận hành 28tr (Biên 28%)',
    sourceFields: ['dw.fact_sales.estimated_net_profit', 'ad_spend_monthly.amount'],
    group: 'operating',
  },
  operatingMargin: {
    name: 'Biên lợi nhuận vận hành',
    formula: 'Lợi nhuận vận hành ÷ Doanh thu × 100%',
    description: 'Phần trăm doanh thu còn lại sau tất cả chi phí bán hàng. Mục tiêu: ≥ 10% cho SME thời trang.',
    businessMeaning: 'Biên < 5%: kinh doanh biên mỏng, rủi ro cao. Biên > 20%: rất tốt.',
    example: 'LN vận hành 28tr ÷ Doanh thu 100tr = Biên vận hành 28%',
    sourceFields: ['dw.fact_sales.estimated_net_profit', 'ad_spend_monthly.amount'],
    group: 'operating',
  },
  netAfterFees: {
    name: 'LN sau phí sàn',
    formula: 'Lợi nhuận gộp − Phí sàn − Phí TT − Packaging − Shipping',
    description: 'Lợi nhuận sau khi trừ toàn bộ phí sàn TMĐT và vận chuyển. Chưa trừ chi phí quảng cáo.',
    businessMeaning: 'Đây là điểm hòa vốn trước QC — nếu âm thì không chạy QC cũng đã lỗ từ phí sàn.',
    example: 'LN gộp 40tr − Phí sàn 8tr − Ship 3tr = LN sau phí sàn 29tr',
    sourceFields: ['dw.fact_sales.estimated_net_profit'],
    group: 'operating',
  },
  adSpend: {
    name: 'Chi phí quảng cáo (QC)',
    formula: 'SUM(ad_spend_monthly.amount) trong kỳ',
    description: 'Tổng chi phí quảng cáo nhập tay theo kênh/tháng: Shopee Ads, TikTok Ads, Lazada Ads.',
    businessMeaning: 'Chi phí QC < 20% doanh thu là hiệu quả. Nếu chưa nhập → ROAS và ACOS không tính được.',
    example: 'Shopee 5tr + TikTok 8tr + Lazada 3tr = Tổng QC tháng 5: 16tr',
    sourceFields: ['public.ad_spend_monthly'],
    group: 'marketing',
  },
  roas: {
    name: 'ROAS — Hiệu quả quảng cáo',
    formula: 'Doanh thu ÷ Chi phí quảng cáo',
    description: '1 đồng chi cho quảng cáo tạo ra bao nhiêu đồng doanh thu. ROAS ≥ 4× thường được coi là hiệu quả.',
    businessMeaning: 'ROAS < 2× cần xem lại nhắm mục tiêu hoặc nội dung quảng cáo.',
    example: 'Chi QC 10tr, doanh thu 50tr → ROAS = 5× (tốt). ROAS = 1.5× → đang lỗ QC',
    sourceFields: ['ad_spend_monthly.amount', 'dw.fact_sales.net_revenue'],
    group: 'marketing',
  },
  acos: {
    name: 'ACOS — Tỷ lệ chi phí QC',
    formula: 'Chi phí quảng cáo ÷ Doanh thu × 100%',
    description: 'Phần trăm doanh thu phải chi cho quảng cáo. ACOS thấp = quảng cáo hiệu quả hơn. Nghịch đảo của ROAS.',
    businessMeaning: 'ACOS = 1/ROAS × 100. ACOS mục tiêu ≤ 15–20% cho thời trang online.',
    example: 'ACOS 20% = cứ 100đ doanh thu thì chi 20đ QC → ROAS tương đương 5×',
    sourceFields: ['ad_spend_monthly.amount', 'dw.fact_sales.net_revenue'],
    group: 'marketing',
  },
  orders: {
    name: 'Số đơn hàng',
    formula: 'COUNT(orders) trong kỳ đã chọn',
    description: 'Tổng số đơn hàng phát sinh trong khoảng thời gian đã chọn, bao gồm mọi trạng thái.',
    businessMeaning: 'Số đơn tăng nhưng doanh thu không tăng → giá bán giảm hoặc sản phẩm giá thấp chiếm ưu thế.',
    example: '320 đơn/tháng = trung bình ~10 đơn/ngày',
    sourceFields: ['dw.fact_sales.order_count'],
    group: 'customer',
  },
  aov: {
    name: 'Giá trị đơn trung bình (AOV)',
    formula: 'Doanh thu thuần ÷ Số đơn hàng',
    description: 'Mỗi đơn hàng trung bình mang lại bao nhiêu doanh thu. AOV cao → khách mua nhiều hoặc giá trị cao hơn.',
    businessMeaning: 'Tăng AOV bằng bundle, upsell, cross-sell thay vì chỉ tăng số đơn.',
    example: 'Doanh thu 100tr ÷ 200 đơn = AOV 500.000đ/đơn',
    sourceFields: ['dw.fact_sales.net_revenue', 'dw.fact_sales.order_count'],
    group: 'customer',
  },
  newCustomers: {
    name: 'Khách hàng mới',
    formula: 'COUNT(customers) lần đầu mua trong kỳ',
    description: 'Số khách hàng phát sinh đơn hàng đầu tiên trong kỳ. Phản ánh tốc độ mở rộng tệp khách.',
    businessMeaning: 'KH mới tốn chi phí QC cao hơn KH cũ. Cần cân bằng giữa acquisition và retention.',
    example: 'Tháng này 85 KH mới → tăng 12% so tháng trước → chiến lược QC đang hiệu quả',
    sourceFields: ['dw.dim_customer', 'dw.fact_sales'],
    group: 'customer',
  },
  retentionRate: {
    name: 'Tỷ lệ giữ chân',
    formula: 'Khách mua ≥2 lần ÷ Tổng khách hàng × 100%',
    description: 'Phần trăm khách hàng quay lại mua ít nhất lần thứ hai. Tỷ lệ cao cho thấy sản phẩm/dịch vụ tốt.',
    businessMeaning: 'Tăng retention 5% có thể tăng lợi nhuận 25–95% (theo Reichheld). Chi phí giữ KH cũ < 5× chi phí tìm KH mới.',
    example: 'Retention 40% = cứ 10 khách thì 4 người quay lại mua thêm. Ngành thời trang tốt: 30–50%',
    sourceFields: ['dw.dim_customer', 'dw.fact_sales'],
    group: 'customer',
  },
  conversionRate: {
    name: 'Tỷ lệ chuyển đổi',
    formula: 'Số đơn hàng ÷ Số lượt xem sản phẩm × 100%',
    description: 'Phần trăm người xem sản phẩm thực sự đặt mua. Cần dữ liệu traffic từ sàn TMĐT.',
    businessMeaning: 'Conversion thấp → cần cải thiện ảnh sản phẩm, mô tả, đánh giá hoặc giá cả.',
    example: 'Conversion 3% = cứ 100 lượt xem thì 3 người đặt hàng. Thời trang online: 2–5%',
    sourceFields: ['Shopee Insight', 'Lazada Analytics', 'TikTok Shop Analytics'],
    group: 'customer',
  },
  businessNetProfit: {
    name: 'Lợi nhuận doanh nghiệp ròng',
    formula: 'Lợi nhuận vận hành − Chi phí vận hành',
    description: 'Lợi nhuận cuối cùng sau khi trừ tất cả chi phí doanh nghiệp (lương, kho, điện nước...)',
    businessMeaning: 'Đây là "bottom line" thực sự của doanh nghiệp — số tiền thực sự kiếm được sau mọi chi phí.',
    example: 'LN vận hành 28tr − Lương 10tr − Kho 3tr − Điện 1tr = LN ròng 14tr',
    sourceFields: ['dw.fact_sales (via FinanceController)', 'public.expenses'],
    group: 'pnl',
  },
}

// Nhóm KPI để hiển thị có tổ chức
export const KPI_GROUPS = {
  revenue:  { label: 'Doanh thu & Chi phí hàng', icon: 'payments',          color: '#6366F1' },
  operating:{ label: 'Hiệu quả vận hành',         icon: 'trending_up',       color: '#10B981' },
  marketing:{ label: 'Hiệu quả quảng cáo',        icon: 'ads_click',         color: '#EC4899' },
  customer: { label: 'Khách hàng',                 icon: 'people',            color: '#3B82F6' },
  pnl:      { label: 'P&L tổng hợp',              icon: 'account_balance',   color: '#8B5CF6' },
}
