// Mock data khách hàng – 10 khách hàng mẫu thực tế (tên VN, SĐT VN)
export const MOCK_CUSTOMERS = [
  {
    id: 1, customer_id: 1, customer_code: 'KH-001',
    full_name: 'Nguyễn Thị Lan Anh', email: 'lananh.nguyen@gmail.com',
    province: 'TP. Hồ Chí Minh', region: 'Miền Nam',
    segment_label: 'VIP', total_orders: 45, total_revenue: 18500000,
    avg_order_value: 411111, last_order_date: '2026-04-15',
  },
  {
    id: 2, customer_id: 2, customer_code: 'KH-002',
    full_name: 'Trần Văn Minh', email: 'minhtr@yahoo.com',
    province: 'Hà Nội', region: 'Miền Bắc',
    segment_label: 'REGULAR', total_orders: 12, total_revenue: 3240000,
    avg_order_value: 270000, last_order_date: '2026-04-10',
  },
  {
    id: 3, customer_id: 3, customer_code: 'KH-003',
    full_name: 'Lê Thị Hương', email: 'huongle.shop@gmail.com',
    province: 'Đà Nẵng', region: 'Miền Trung',
    segment_label: 'VIP', total_orders: 38, total_revenue: 14200000,
    avg_order_value: 373684, last_order_date: '2026-04-17',
  },
  {
    id: 4, customer_id: 4, customer_code: 'KH-004',
    full_name: 'Phạm Đức Thắng', email: 'thang.pham2004@gmail.com',
    province: 'Bình Dương', region: 'Miền Nam',
    segment_label: 'NEW', total_orders: 2, total_revenue: 450000,
    avg_order_value: 225000, last_order_date: '2026-04-16',
  },
  {
    id: 5, customer_id: 5, customer_code: 'KH-005',
    full_name: 'Hoàng Thị Mỹ Linh', email: 'mylinh.hoang@outlook.com',
    province: 'Cần Thơ', region: 'Miền Nam',
    segment_label: 'REGULAR', total_orders: 8, total_revenue: 2100000,
    avg_order_value: 262500, last_order_date: '2026-03-28',
  },
  {
    id: 6, customer_id: 6, customer_code: 'KH-006',
    full_name: 'Vũ Tuấn Anh', email: 'tuananh.vu@gmail.com',
    province: 'Hải Phòng', region: 'Miền Bắc',
    segment_label: 'VIP', total_orders: 52, total_revenue: 22750000,
    avg_order_value: 437500, last_order_date: '2026-04-14',
  },
  {
    id: 7, customer_id: 7, customer_code: 'KH-007',
    full_name: 'Đặng Ngọc Bích', email: 'bich.dang99@gmail.com',
    province: 'Hà Nội', region: 'Miền Bắc',
    segment_label: 'INACTIVE', total_orders: 5, total_revenue: 895000,
    avg_order_value: 179000, last_order_date: '2025-11-12',
  },
  {
    id: 8, customer_id: 8, customer_code: 'KH-008',
    full_name: 'Ngô Thị Thu Thảo', email: 'thuthao.ngo@hotmail.com',
    province: 'TP. Hồ Chí Minh', region: 'Miền Nam',
    segment_label: 'REGULAR', total_orders: 15, total_revenue: 4320000,
    avg_order_value: 288000, last_order_date: '2026-04-08',
  },
  {
    id: 9, customer_id: 9, customer_code: 'KH-009',
    full_name: 'Bùi Minh Quân', email: 'minhquan.bui@gmail.com',
    province: 'Nghệ An', region: 'Miền Trung',
    segment_label: 'NEW', total_orders: 1, total_revenue: 189000,
    avg_order_value: 189000, last_order_date: '2026-04-18',
  },
  {
    id: 10, customer_id: 10, customer_code: 'KH-010',
    full_name: 'Trịnh Thị Thanh Hà', email: 'thanhha.trinh@gmail.com',
    province: 'Khánh Hòa', region: 'Miền Trung',
    segment_label: 'VIP', total_orders: 29, total_revenue: 11600000,
    avg_order_value: 400000, last_order_date: '2026-04-12',
  },
]
