// Mock data sản phẩm – 10 sản phẩm mẫu thực tế (tiếng Việt)
export const MOCK_PRODUCTS = [
  {
    id: 1, product_id: 1,
    name: 'Áo thun nam cổ tròn cotton', product_name: 'Áo thun nam cổ tròn cotton',
    sku: 'AT-NAM-001', category: 'Thời trang', brand: 'LocalBrand VN',
    price: 189000, unit_price: 189000, cost_price: 90000,
    stock: 342, total_qty_sold: 1250, total_orders: 980,
    channel: 'Shopee', status: 'active', is_current: true,
  },
  {
    id: 2, product_id: 2,
    name: 'Đầm maxi hoa nhí dáng dài', product_name: 'Đầm maxi hoa nhí dáng dài',
    sku: 'DM-NU-002', category: 'Thời trang', brand: 'Kira Fashion',
    price: 320000, unit_price: 320000, cost_price: 140000,
    stock: 87, total_qty_sold: 650, total_orders: 521,
    channel: 'Lazada', status: 'active', is_current: true,
  },
  {
    id: 3, product_id: 3,
    name: 'Tai nghe không dây Bluetooth 5.3', product_name: 'Tai nghe không dây Bluetooth 5.3',
    sku: 'TN-BT-003', category: 'Điện tử', brand: 'TechSound',
    price: 590000, unit_price: 590000, cost_price: 280000,
    stock: 12, total_qty_sold: 430, total_orders: 398,
    channel: 'TikTok Shop', status: 'low_stock', is_current: true,
  },
  {
    id: 4, product_id: 4,
    name: 'Kem dưỡng ẩm ban đêm SPF 30', product_name: 'Kem dưỡng ẩm ban đêm SPF 30',
    sku: 'KD-AM-004', category: 'Mỹ phẩm', brand: 'VietBeauty',
    price: 255000, unit_price: 255000, cost_price: 95000,
    stock: 560, total_qty_sold: 2100, total_orders: 1870,
    channel: 'Shopee', status: 'active', is_current: true,
  },
  {
    id: 5, product_id: 5,
    name: 'Bình giữ nhiệt inox 500ml', product_name: 'Bình giữ nhiệt inox 500ml',
    sku: 'BG-NI-005', category: 'Gia dụng', brand: 'HomeLife',
    price: 145000, unit_price: 145000, cost_price: 60000,
    stock: 210, total_qty_sold: 3200, total_orders: 2980,
    channel: 'Shopee', status: 'active', is_current: true,
  },
  {
    id: 6, product_id: 6,
    name: 'Giày thể thao nam đế êm', product_name: 'Giày thể thao nam đế êm',
    sku: 'GT-TT-006', category: 'Giày dép', brand: 'StepUp VN',
    price: 650000, unit_price: 650000, cost_price: 310000,
    stock: 45, total_qty_sold: 187, total_orders: 165,
    channel: 'Lazada', status: 'active', is_current: true,
  },
  {
    id: 7, product_id: 7,
    name: 'Trà sữa bột pha liền 3in1 (hộp 20 gói)', product_name: 'Trà sữa bột pha liền 3in1',
    sku: 'TS-BOT-007', category: 'Thực phẩm', brand: 'MilkTea House',
    price: 95000, unit_price: 95000, cost_price: 42000,
    stock: 1500, total_qty_sold: 8700, total_orders: 6200,
    channel: 'TikTok Shop', status: 'active', is_current: true,
  },
  {
    id: 8, product_id: 8,
    name: 'Đèn LED cảm ứng pin sạc USB', product_name: 'Đèn LED cảm ứng pin sạc USB',
    sku: 'DL-LED-008', category: 'Gia dụng', brand: 'BrightHome',
    price: 125000, unit_price: 125000, cost_price: 55000,
    stock: 0, total_qty_sold: 540, total_orders: 498,
    channel: 'Facebook', status: 'inactive', is_current: true,
  },
  {
    id: 9, product_id: 9,
    name: 'Máy massage cầm tay mini 5 đầu', product_name: 'Máy massage cầm tay mini 5 đầu',
    sku: 'MM-CH-009', category: 'Sức khỏe', brand: 'HealthPro',
    price: 380000, unit_price: 380000, cost_price: 165000,
    stock: 78, total_qty_sold: 312, total_orders: 289,
    channel: 'Lazada', status: 'active', is_current: true,
  },
  {
    id: 10, product_id: 10,
    name: 'Túi tote canvas in hình thỏ', product_name: 'Túi tote canvas in hình thỏ',
    sku: 'TT-CNV-010', category: 'Phụ kiện', brand: 'CuteStyle',
    price: 85000, unit_price: 85000, cost_price: 32000,
    stock: 230, total_qty_sold: 1670, total_orders: 1480,
    channel: 'TikTok Shop', status: 'active', is_current: true,
  },
]
